import type {
  RemoteAccount,
  RemoteCategoryGroup,
  RemotePayee,
  RemoteTransaction,
} from '../local/types.js';
import type { FakeBudgetData } from './fakeYnabClient.js';

export const BUDGET_ID = 'budget-1';

export const baseAccount: RemoteAccount = {
  id: 'acct-checking',
  name: 'Checking',
  type: 'checking',
  on_budget: true,
  closed: false,
  note: null,
  balance: 1_000_000,
  cleared_balance: 1_000_000,
  uncleared_balance: 0,
  transfer_payee_id: null,
  direct_import_linked: false,
  direct_import_in_error: false,
  deleted: false,
};

export const baseCreditAccount: RemoteAccount = {
  id: 'acct-credit',
  name: 'Visa',
  type: 'creditCard',
  on_budget: true,
  closed: false,
  note: null,
  balance: -50_000,
  cleared_balance: -50_000,
  uncleared_balance: 0,
  transfer_payee_id: null,
  direct_import_linked: true,
  direct_import_in_error: false,
  deleted: false,
};

export const baseCategoryGroups: RemoteCategoryGroup[] = [
  {
    id: 'group-needs',
    name: 'Monthly Needs',
    hidden: false,
    deleted: false,
    categories: [
      {
        id: 'cat-groceries',
        category_group_id: 'group-needs',
        name: 'Groceries',
        hidden: false,
        budgeted: 500_000,
        activity: -120_000,
        balance: 380_000,
        goal_type: null,
        goal_target: null,
        deleted: false,
      },
      {
        id: 'cat-rent',
        category_group_id: 'group-needs',
        name: 'Rent',
        hidden: false,
        budgeted: 1_500_000,
        activity: -1_500_000,
        balance: 0,
        goal_type: null,
        goal_target: null,
        deleted: false,
      },
      {
        id: 'cat-overspent',
        category_group_id: 'group-needs',
        name: 'Dining Out',
        hidden: false,
        budgeted: 100_000,
        activity: -150_000,
        balance: -50_000,
        goal_type: null,
        goal_target: null,
        deleted: false,
      },
    ],
  },
];

export const basePayees: RemotePayee[] = [
  {
    id: 'payee-grocer',
    name: 'Local Grocer',
    transfer_account_id: null,
    deleted: false,
  },
  {
    id: 'payee-employer',
    name: 'Employer Inc',
    transfer_account_id: null,
    deleted: false,
  },
];

export const baseTransactions: RemoteTransaction[] = [
  {
    id: 'tx-grocery-1',
    date: '2026-04-30',
    amount: -45_000,
    memo: null,
    cleared: 'cleared',
    approved: true,
    flag_color: null,
    account_id: 'acct-credit',
    payee_id: 'payee-grocer',
    payee_name: 'Local Grocer',
    category_id: 'cat-groceries',
    category_name: 'Groceries',
    transfer_account_id: null,
    transfer_transaction_id: null,
    matched_transaction_id: null,
    import_id: null,
    import_payee_name: null,
    import_payee_name_original: null,
    debt_transaction_type: null,
    deleted: false,
    subtransactions: [],
  },
  {
    id: 'tx-grocery-uncategorized',
    date: '2026-05-01',
    amount: -32_500,
    memo: 'Needs categorization',
    cleared: 'cleared',
    approved: false,
    flag_color: null,
    account_id: 'acct-credit',
    payee_id: 'payee-grocer',
    payee_name: 'Local Grocer',
    category_id: null,
    category_name: null,
    transfer_account_id: null,
    transfer_transaction_id: null,
    matched_transaction_id: null,
    import_id: null,
    import_payee_name: null,
    import_payee_name_original: null,
    debt_transaction_type: null,
    deleted: false,
    subtransactions: [],
  },
  {
    id: 'tx-paycheck',
    date: '2026-04-28',
    amount: 2_500_000,
    memo: 'Paycheck',
    cleared: 'cleared',
    approved: true,
    flag_color: null,
    account_id: 'acct-checking',
    payee_id: 'payee-employer',
    payee_name: 'Employer Inc',
    category_id: 'cat-inflow',
    category_name: 'Inflow: Ready to Assign',
    transfer_account_id: null,
    transfer_transaction_id: null,
    matched_transaction_id: null,
    import_id: null,
    import_payee_name: null,
    import_payee_name_original: null,
    debt_transaction_type: null,
    deleted: false,
    subtransactions: [],
  },
  {
    id: 'tx-transfer',
    date: '2026-04-29',
    amount: -100_000,
    memo: null,
    cleared: 'cleared',
    approved: true,
    flag_color: null,
    account_id: 'acct-checking',
    payee_id: null,
    payee_name: 'Transfer : Visa',
    category_id: null,
    category_name: null,
    transfer_account_id: 'acct-credit',
    transfer_transaction_id: 'tx-transfer-other-side',
    matched_transaction_id: null,
    import_id: null,
    import_payee_name: null,
    import_payee_name_original: null,
    debt_transaction_type: null,
    deleted: false,
    subtransactions: [],
  },
];

export function makeBaseData(): FakeBudgetData {
  return {
    budget: {
      id: BUDGET_ID,
      name: 'Family Budget',
      first_month: '2024-01-01',
      last_month: '2026-05-01',
      currency_iso_code: 'USD',
    },
    accounts: [baseAccount, baseCreditAccount],
    categories: baseCategoryGroups,
    payees: basePayees,
    transactions: baseTransactions,
  };
}
